datasource:
  type: csv
  path: "./sample.csv"

components:
  profiler: pandas
  suggester: 
    type: ollama
    model: gemma3:1b
  validator: great_expectations

columns_to_validate:
  - age
  - user_email