datasource:
  type: postgresql
  host: localhost
  port: 5432
  user: your_user
  password: your_password
  db: your_db
  query: "SELECT name, age, email FROM public.your_table LIMIT 1000"

components:
  profiler: pandas
  suggester: 
    type: ollama
    model: gemma3:1b
  validator: great_expectations

columns_to_validate:
  - age
  - user_email